INSERT INTO books (id,is_delete, title, author, description, year) VALUES
(22,1, "СИ++ И КОМПЬЮТЕРНАЯ ГРАФИКА", "Андрей Богуславский", "Учебник по языку C++ с основами компьютерной графики", ""),
(23,0, "Программирование на языке Go!", "Марк Саммерфильд", "Практическое руководство по программированию на языке Go!", ""),
(25,0, "Толковый словарь сетевых терминов и аббревиатур", "М., Вильямс", "Словарь, содержащий толкования основных терминов и аббревиатур, используемых в сетевых технологиях", ""),
(26,0, "Python for Data Analysis", "Уэс Маккинни", "Руководство по анализу данных с использованием языка программирования Python", ""),
(27,0, "Thinking in Java (4th Edition)", "Брюс Эккель", "Учебник по языку программирования Java, ориентированный на развитие навыков мышления в программировании", ""),
(29,0, "Introduction to Algorithms", "Томас Кормен, Чарльз Лейзерсон, Рональд Ривест, Клиффорд Штайн", "Классическое введение в алгоритмы и структуры данных", ""),
(31,0, "JavaScript Pocket Reference", "Дэвид Флэнаган", "Компактное справочное руководство по языку программирования JavaScript", ""),
(32,0, "Adaptive Code via C#: Class and Interface Design, Design Patterns, and SOLID Principles", "Гэри Маклин Холл", "Руководство по разработке адаптивного кода с использованием языка программирования C#", ""),
(33,0, "SQL: The Complete Reference", "Джеймс Р. Грофф", "Исчерпывающее руководство по языку структурированных запросов SQL", ""),
(34,0, "PHP and MySQL Web Development", "Люк Веллинг", "Практическое руководство по веб-разработке с использованием PHP и MySQL", ""),
(35,0, "Статистический анализ и визуализация данных с помощью R", "Сергей Мастицкий", "Введение в статистический анализ и визуализацию данных, используя язык программирования R", ""),
(36,0, "Computer Coding for Kids", "Джон Вудкок", "Введение в компьютерное программирование для детей", ""),
(37,0, "Exploring Arduino: Tools and Techniques for Engineering Wizardry", "Джереми Блум", "Практическое руководство по использованию платформы Arduino для создания различных устройств", ""),
(38,0, "Программирование микроконтроллеров для начинающих и не только", "А. Белов", "Руководство по программированию микроконтроллеров с нуля", ""),
(39,0, "The Internet of Things", "Сэмюэл Грингард", "Изучение концепций и принципов Интернета вещей", ""),
(40,0, "Sketching User Experiences: The Workbook", "Сет Гринберг", "Практическое руководство по проектированию пользовательских интерфейсов и пользовательских взаимодействий", ""),
(41,0, "InDesign CS6", "Александр Сераков", "Руководство по программе верстки InDesign CS6", ""),
(42,0, "Адаптивный дизайн. Делаем сайты для любых устройств", "Тим Кедлек", "Учебное пособие по созданию адаптивного дизайна для веб-сайтов", ""),
(43,0, "Android для разработчиков", "Пол Дейтел, Харви Дейтел", "Руководство по разработке приложений под платформу Android", ""),
(44,0, "Clean Code: A Handbook of Agile Software Craftsmanship", "Роберт Мартин", "Руководство по написанию чистого и эффективного программного кода", ""),
(45,0, "Swift Pocket Reference: Programming for iOS and OS X", "Энтони Грей", "Краткое справочное руководство по программированию на языке Swift для платформы iOS и OS X", ""),
(46,0, "NoSQL Distilled: A Brief Guide to the Emerging World of Polyglot Persistence", "Мартин Фаулер, Прамодкумар Дж. Садаладж", "Краткое руководство по NoSQL-базам данных и принципам полиглотной устойчивости", ""),
(47,0, "Head First Ruby", "Джей Макгаврен", "Введение в язык программирования Ruby через нестандартный и интерактивный подход", ""),
(48,0, "Practical Vim", "Дрю Нейл", "Практическое руководство по эффективному использованию текстового редактора Vim", ""),
(49,0, "HTML and CSS: Design and Build Websites", "Джон Дакетт", "Introduction to HTML and CSS for building websites", ""),
(50,0, "The Pragmatic Programmer: Your Journey to Mastery", "Эндрю Хант, Дэвид Томас", "Guide to becoming a more efficient and effective programmer", ""),
(51,0, "Java Concurrency in Practice", "Брайан Гётц", "Comprehensive guide to writing concurrent programs in Java", ""),
(52,0, "Ruby on Rails Tutorial: Learn Web Development with Rails", "Майкл Хартл", "Step-by-step tutorial on building web applications with Ruby on Rails", ""),
(53,1, "Deep Learning", "Иэн Гудфеллоу, Йошуа Бенжио, Аарон Курвилль", "Comprehensive introduction to deep learning techniques and algorithms", ""),
(54,1, "Eloquent JavaScript: A Modern Introduction to Programming", "Мариейн Хавербеке", "Introduction to JavaScript programming", ""),
(55,1, "C Programming Language", "Брайан Керниган, Деннис Ритчи", "Classic book on programming in the C language", ""),
(56,1, "Machine Learning Yearning", "Эндрю Янг", "Practical guide to developing and deploying machine learning systems", ""),
(57,1, "Dive Into Python 3", "Марк Пилгрим", "Introduction to Python 3 programming language", ""),
(58,1, "The Elements of Computing Systems: Building a Modern Computer from First Principles", "Ниссим Нир", "Guide to building a computer system from the ground up", "");



